language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
env:
  matrix:
    - WTFORMS=WTForms==1.0.5
    - WTFORMS=WTForms~=2.1

install:
  - "pip install $WTFORMS"
  - pip install -e ".[test]"
script:
  - isort --recursive --diff wtforms_components tests && isort --recursive --check-only wtforms_components tests
  - flake8 wtforms_components tests
  - py.test
